### ISSUE TITLE
Create an ERD reflective of the proposed DB schema

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/api.mozillascience.org#3]
Here's a WIP:
https://drive.google.com/file/d/0B1u5GiGrg8FDcFo2dmRBeVBpUjQ/view?usp=sharing

cc @simonwex, @acabunoc, @gvn

**Comment by gvn** [comment]
This is very hard to read...can you upload it at a higher resolution?

**Comment by alicoding** [comment]
This draw.io shareable link is terrible, so I've made this redpen for people to look at and comment if you think something is wrong in the ERD https://redpen.io/dkccfdefc73fcda519

**Comment by gideonthomas** [comment]
Updated version: https://redpen.io/p/hjfd445b0b28768fee

cc @kristinashu, @hannahkane
