### ISSUE TITLE
Update config vars for staging and production

### ISSUE THREAD

**Issue by arush0311** [mozilla/api.mozillascience.org#87]
We would need these config vars in staging and production:

USE_S3=True
GITHUB_AUTH=True
SOCIAL_AUTH_GITHUB_KEY(different for staging and prod)
SOCIAL_AUTH_GITHUB_SECRET(different for staging and prod)
AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY
AWS_STORAGE_BUCKET_NAME
AWS_S3_CUSTOM_DOMAIN
AWS_LOCATION='uploads/'
FILEBROWSER_DIRECTORY='uploads/'

@cadecairos Can you look at this?

**Comment by cadecairos** [comment]
@arush0311 Did you need me to get and set these variables on a Heroku app?

**Comment by arush0311** [comment]
yeah. Can you do that please?

**Comment by cadecairos** [comment]
Sure, which Heroku apps are we working with

**Comment by arush0311** [comment]
staging and production apps? I don't quite follow.

**Comment by arush0311** [comment]
Oh and also this https://github.com/mozilla/api.mozillascience.org/pull/84

**Comment by cadecairos** [comment]
> staging and production apps? I don't quite follow.

I just want to make sure we're talking about "https://dashboard.heroku.com/apps/api-mozillascience-staging" and "https://dashboard.heroku.com/apps/api-mozillascience-production"

**Comment by arush0311** [comment]
yeah these.

**Comment by cadecairos** [comment]
wont-fixing this due to inactivity.
