### ISSUE TITLE
Investigate s3 error in staging

### ISSUE THREAD

**Issue by arush0311** [mozilla/api.mozillascience.org#98]
When clicking on media library, a server error occurs. As the logs are not visible on staging i created a review app and it says something like this:
```
 botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the ListObjects operation: Access Denied
```
I think it is related to s3 permissions.

**Comment by gideonthomas** [comment]
Hmm so the S3 permissions are correct.
Maybe the credentials are incorrect. I'll try generating new ones

**Comment by cadecairos** [comment]
This is working now - I set it up exactly how I should have in the first place (using the mofo-assets-staging bucket, and a mozillascience prefix)

**Comment by gideonthomas** [comment]
@arush0311, this should be working now. Feel free to reopen if it isn't.

Thanks @cadecairos!
